region: cn-shenzhen
app:
  name: jamstack-api-test
  # 可选服务配置 'logConfig', 'vpcConfig', 'nasConfig', 'role'
  # 可选函数配置
  # runtime: string # 默认：nodejs12,
  # handler: string # 默认：index.handler
  # description: string # 默认：''
  # memorySize: 128
  # timeout: 10
  # initializationTimeout: 3
  # initializer: string
  # instanceConcurrency: 1
  # instanceType: e1 | c1 # 默认：e1
  # layers: string[],
  # environmentVariables: { [key: string]: string }

customDomain: # 选填【不支持私有配置】，默认：
  domainName: auto
  protocol: HTTP
  # protocol: HTTP,HTTPS
  # certConfig:
  #   certName: xxx
  #   certificate: xxx
  #   privateKey: xxx

  # routeConfigs 的 path生成规则根据 s.yml 里面的 route 配置


http: # 选填， 默认值
  - authType: anonymous
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - HEAD