region: cn-shenzhen
app:
  name: dk-tablestore-demo
  role:
    name: fcdeploydefaultrole-dk-tablestore-demo
    policies:
      - AliyunECSNetworkInterfaceManagementAccess
      - AliyunOTSFullAccess
  runtime: nodejs12
  memory: 1152
  timeout: 60
  concurrency: 1
customDomain: # 选填【不支持私有配置】，默认：
  domainName: auto
  protocol: HTTP
http: # 选填， 默认值
  - authType: anonymous
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - HEAD
